"""
PDF SERVICE
============
Purpose: Generate PDF files from PhantomAI data.

Generates:
- Conversation PDFs
- Notes PDFs
- Tasks PDFs

Design goals:
- Reliable PDF generation
- Safe handling of user/AI text
- Professional formatting
- No dependency on emoji fonts
"""

from io import BytesIO
from datetime import datetime
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle,
)
from reportlab.lib.enums import TA_LEFT


# ============================================================
# HELPERS
# ============================================================

def _safe_text(value) -> str:
    """
    Convert a value to safe text for ReportLab Paragraph.

    ReportLab Paragraph supports a small amount of XML-like
    markup, so user-generated content must be escaped first.
    """
    if value is None:
        return ""

    return escape(str(value)).replace("\n", "<br/>")


def _create_document(buffer: BytesIO) -> SimpleDocTemplate:
    """
    Create a standard PhantomAI PDF document.
    """
    return SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=54,
        bottomMargin=54,
        title="PhantomAI Report",
        author="PhantomAI",
    )


def _get_styles():
    """
    Create shared PDF styles.
    """
    styles = getSampleStyleSheet()

    return {
        "title": ParagraphStyle(
            "PhantomTitle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#1a3a6e"),
            spaceAfter=10,
        ),

        "subtitle": ParagraphStyle(
            "PhantomSubtitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=colors.grey,
            spaceAfter=4,
        ),

        "section": ParagraphStyle(
            "PhantomSection",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#1a3a6e"),
            spaceBefore=8,
            spaceAfter=6,
        ),

        "normal": ParagraphStyle(
            "PhantomNormal",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10.5,
            leading=15,
            textColor=colors.HexColor("#222222"),
            alignment=TA_LEFT,
            spaceAfter=6,
        ),

        "user_label": ParagraphStyle(
            "UserLabel",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=colors.HexColor("#1a3a6e"),
            spaceAfter=3,
        ),

        "assistant_label": ParagraphStyle(
            "AssistantLabel",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=colors.HexColor("#333333"),
            spaceAfter=3,
        ),

        "message": ParagraphStyle(
            "Message",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            leftIndent=12,
            rightIndent=6,
            textColor=colors.HexColor("#222222"),
            spaceAfter=8,
        ),

        "italic": ParagraphStyle(
            "PhantomItalic",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=9,
            textColor=colors.grey,
            spaceAfter=6,
        ),
    }


def _add_footer(canvas, doc):
    """
    Add a simple footer to every page.
    """
    canvas.saveState()

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)

    canvas.drawString(
        doc.leftMargin,
        30,
        "Generated by PhantomAI"
    )

    canvas.drawRightString(
        letter[0] - doc.rightMargin,
        30,
        f"Page {doc.page}"
    )

    canvas.restoreState()


# ============================================================
# CONVERSATION PDF
# ============================================================

def generate_conversation_pdf(conversation_data: dict) -> BytesIO:
    """
    Generate a PDF from a conversation.

    Expected structure:

    {
        "title": "My Chat",
        "messages": [
            {
                "role": "user",
                "content": "Hello"
            },
            {
                "role": "assistant",
                "content": "Hello! How can I help?"
            }
        ],
        "created_at": "2026-08-04"
    }

    Returns:
        BytesIO containing the generated PDF.
    """

    buffer = BytesIO()
    doc = _create_document(buffer)
    styles = _get_styles()

    story = []

    # --------------------------------------------------------
    # Header
    # --------------------------------------------------------

    title = conversation_data.get("title") or "Conversation"

    story.append(
        Paragraph(
            _safe_text(title),
            styles["title"]
        )
    )

    story.append(
        Paragraph(
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            styles["subtitle"]
        )
    )

    created_at = conversation_data.get("created_at")

    if created_at:
        story.append(
            Paragraph(
                f"Started: {_safe_text(created_at)}",
                styles["subtitle"]
            )
        )

    story.append(Spacer(1, 16))

    # --------------------------------------------------------
    # Messages
    # --------------------------------------------------------

    messages = conversation_data.get("messages") or []

    if not messages:
        story.append(
            Paragraph(
                "No messages were found in this conversation.",
                styles["normal"]
            )
        )

    for message in messages:
        role = message.get("role", "unknown")
        content = message.get("content", "")

        if role == "user":
            label = "You"
            label_style = styles["user_label"]

        elif role == "assistant":
            label = "PhantomAI"
            label_style = styles["assistant_label"]

        else:
            label = str(role).capitalize()
            label_style = styles["assistant_label"]

        story.append(
            Paragraph(
                f"<b>{_safe_text(label)}</b>",
                label_style
            )
        )

        story.append(
            Paragraph(
                _safe_text(content),
                styles["message"]
            )
        )

        story.append(Spacer(1, 5))

    # --------------------------------------------------------
    # End
    # --------------------------------------------------------

    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            "End of Conversation",
            styles["italic"]
        )
    )

    doc.build(
        story,
        onFirstPage=_add_footer,
        onLaterPages=_add_footer,
    )

    buffer.seek(0)

    return buffer


# ============================================================
# NOTES PDF
# ============================================================

def generate_notes_pdf(notes_data: list) -> BytesIO:
    """
    Generate a PDF from notes.

    Expected structure:

    [
        {
            "title": "Note 1",
            "content": "My note...",
            "created_at": "2026-08-04"
        }
    ]

    Returns:
        BytesIO containing the generated PDF.
    """

    buffer = BytesIO()
    doc = _create_document(buffer)
    styles = _get_styles()

    story = []

    # Header
    story.append(
        Paragraph(
            "My Notes",
            styles["title"]
        )
    )

    story.append(
        Paragraph(
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            styles["subtitle"]
        )
    )

    story.append(Spacer(1, 16))

    if not notes_data:
        story.append(
            Paragraph(
                "No notes were found.",
                styles["normal"]
            )
        )

    for note in notes_data:
        title = note.get("title") or "Untitled Note"
        content = note.get("content") or ""

        story.append(
            Paragraph(
                _safe_text(title),
                styles["section"]
            )
        )

        story.append(
            Paragraph(
                _safe_text(content),
                styles["normal"]
            )
        )

        created_at = note.get("created_at")

        if created_at:
            story.append(
                Paragraph(
                    f"Created: {_safe_text(created_at)}",
                    styles["italic"]
                )
            )

        story.append(Spacer(1, 10))

    doc.build(
        story,
        onFirstPage=_add_footer,
        onLaterPages=_add_footer,
    )

    buffer.seek(0)

    return buffer


# ============================================================
# TASKS PDF
# ============================================================

def generate_tasks_pdf(tasks_data: list) -> BytesIO:
    """
    Generate a PDF from tasks.

    Expected structure:

    [
        {
            "title": "Task 1",
            "status": "pending",
            "priority": "high",
            "due_date": "2026-08-10"
        }
    ]

    Returns:
        BytesIO containing the generated PDF.
    """

    buffer = BytesIO()
    doc = _create_document(buffer)
    styles = _get_styles()

    story = []

    # Header
    story.append(
        Paragraph(
            "My Tasks",
            styles["title"]
        )
    )

    story.append(
        Paragraph(
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            styles["subtitle"]
        )
    )

    story.append(Spacer(1, 16))

    # --------------------------------------------------------
    # Table
    # --------------------------------------------------------

    table_data = [
        [
            Paragraph("<b>Task</b>", styles["normal"]),
            Paragraph("<b>Status</b>", styles["normal"]),
            Paragraph("<b>Priority</b>", styles["normal"]),
            Paragraph("<b>Due Date</b>", styles["normal"]),
        ]
    ]

    for task in tasks_data or []:

        title = _safe_text(task.get("title", ""))
        status = _safe_text(task.get("status", "pending"))
        priority = _safe_text(task.get("priority", "medium"))

        due_date = task.get("due_date")

        if due_date:
            due_date = str(due_date)[:10]
        else:
            due_date = ""

        table_data.append(
            [
                Paragraph(title, styles["normal"]),
                Paragraph(status, styles["normal"]),
                Paragraph(priority, styles["normal"]),
                Paragraph(due_date, styles["normal"]),
            ]
        )

    if len(table_data) == 1:
        table_data.append(
            [
                Paragraph("No tasks found.", styles["normal"]),
                "",
                "",
                "",
            ]
        )

    table = Table(
        table_data,
        colWidths=[230, 85, 85, 85],
        repeatRows=1,
        hAlign="LEFT",
    )

    table.setStyle(
        TableStyle(
            [
                # Header
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#1a3a6e"),
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.white,
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold",
                ),

                # Alignment
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "TOP",
                ),

                # Padding
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),

                # Borders
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#cccccc"),
                ),

                # Body
                (
                    "BACKGROUND",
                    (0, 1),
                    (-1, -1),
                    colors.white,
                ),
            ]
        )
    )

    story.append(table)

    doc.build(
        story,
        onFirstPage=_add_footer,
        onLaterPages=_add_footer,
    )

    buffer.seek(0)

    return buffer

from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)
from reportlab.lib.units import mm


def generate_file_pdf(
    file_name: str,
    file_path: str,
    content: str,
):
    """
    Generate a PDF containing extracted file content.
    """

    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    body_style = styles["BodyText"]
    body_style.leading = 15

    story = []

    story.append(
        Paragraph(
            "PhantomAI File Export",
            title_style,
        )
    )

    story.append(
        Spacer(1, 12)
    )

    story.append(
        Paragraph(
            f"<b>File:</b> {file_name}",
            body_style,
        )
    )

    story.append(
        Paragraph(
            f"<b>Path:</b> {file_path}",
            body_style,
        )
    )

    story.append(
        Spacer(1, 15)
    )

    # Split content into paragraphs
    paragraphs = content.split("\n")

    for paragraph in paragraphs:
        clean_text = (
            paragraph
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )

        if clean_text.strip():
            story.append(
                Paragraph(
                    clean_text,
                    body_style,
                )
            )

            story.append(
                Spacer(1, 6)
            )

    document.build(story)

    buffer.seek(0)

    return buffer